# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/bogdi/OneDrive/Desktop/SCS/Lab6/6.1/FIFO_buffer_IP_Core/FIFO_buffer_IP_Core.srcs/sources_1/ip/fifo32x64/fifo32x64.xci
# IP: The module: 'fifo32x64' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/bogdi/OneDrive/Desktop/SCS/Lab6/6.1/FIFO_buffer_IP_Core/FIFO_buffer_IP_Core.gen/sources_1/ip/fifo32x64/fifo32x64_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo32x64'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/bogdi/OneDrive/Desktop/SCS/Lab6/6.1/FIFO_buffer_IP_Core/FIFO_buffer_IP_Core.srcs/sources_1/ip/fifo32x64/fifo32x64.xci
# IP: The module: 'fifo32x64' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/bogdi/OneDrive/Desktop/SCS/Lab6/6.1/FIFO_buffer_IP_Core/FIFO_buffer_IP_Core.gen/sources_1/ip/fifo32x64/fifo32x64_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo32x64'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
